### ISSUE TITLE
windows minimize problem

### ISSUE THREAD

**Issue by vaniron** [Tauri-WoW-Community-Devs/TauriTSMAppDataFetcher#1]
Can something be done about this? Its 1.2.3 on windows 10 but was making the same in previous versions too.

![tsm](https://user-images.githubusercontent.com/17107410/152115300-fbdfe5e3-0fb4-4782-abb7-59ccafbe1735.gif)

**Comment by query-csharp** [comment]
Fixed in https://github.com/Tauri-WoW-Community-Devs/TauriTSMAppDataFetcher/releases/tag/V1.2.4
